// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkmjkeaqduxrsdwpwdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a21qa2VhcWR1eHJzZHdwd2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDgzMzYsImV4cCI6MjA1OTA4NDMzNn0.Tegouz4Veh8I_pn3LSa2wYd9dFDGJEVXJXiHAAyRu8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);